site_name: AI Learning Path
repo_url: https://github.com/gautamnaik1994/ai-learning-path
repo_name: ai-learning-path
edit_uri: edit/main/docs/
theme:
  features:
    - content.action.edit
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
   - search
   - awesome-nav

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences