nav:
  - Home: index.md
  - Prerequisites: prerequisites.md
  - ML Learning Path: machine-learning-path/index.md
  - DL Learning Path: deep-learning-path/index.md
  - Gen AI Learning Path: gen-ai-learning-path/index.md
  