nav:
  - Home: index.md
  - Prerequisites: prerequisites.md
  - Machine Learning:
      - Introduction: machine-learning/index.md
  - Deep Learning:
      - Introduction: deep-learning/index.md
  - Gen AI Learning Path:
      - Introduction: gen-ai-learning-path/index.md
      - Rag: gen-ai-learning-path/rag.md
      - Agents: gen-ai-learning-path/agents.md
      - MCP: gen-ai-learning-path/mcp.md