nav:
  - Home: index.md
  - Prerequisites: prerequisites.md
  - Gen AI Learning Path:
      - Rag: gen-ai-learning-path/rag.md
      - Agents: gen-ai-learning-path/agents.md
      - MCP: gen-ai-learning-path/mcp.md